#!groovy

// This CI/CD pipeline will execute within the container of a custom Jenkins image that includes the "3scale-toolbox-jenkins" shared library
// Documentation pertaining to this shared library can be found here:
//   1)  https://developers.redhat.com/blog/2019/07/31/using-the-3scale-toolbox-jenkins-shared-library/
//   2)  https://github.com/rh-integration/3scale-toolbox-jenkins/blob/master/README.md

// TO-DO:  Explain why doesn't this groovy functionality just come out of the box with the the 3scale toolbox container image ?
library identifier: '3scale-toolbox-jenkins@master', 
        retriever: modernSCM([$class: 'GitSCMSource',
                              remote: 'https://github.com/sgutierr/3scale-toolbox-jenkins.git',
                              traits: [[$class: 'jenkins.plugins.git.traits.BranchDiscoveryTrait']]])

def service = null

node() {
  stage('Pre-requisites') {
    if (params.OPENAPI_SPECIFICATION_FILE != "openapi-spec-v1.0.json"
     && params.OPENAPI_SPECIFICATION_FILE != "openapi-spec-v1.1.json"
     && params.OPENAPI_SPECIFICATION_FILE != "openapi-spec-v2.0.json"
     && params.OPENAPI_SPECIFICATION_FILE != "openapi-spec-v3.0.json"
     && params.OPENAPI_SPECIFICATION_FILE != "insurance-spec.json"
     && params.OPENAPI_SPECIFICATION_FILE != "stock-spec-v1.0.json"
     && params.OPENAPI_SPECIFICATION_FILE != "stock-spec-v1.1.json"	
     && params.OPENAPI_SPECIFICATION_FILE != "stock-spec-v2.0.json"		
     && params.OPENAPI_SPECIFICATION_FILE != "openapi-spec-v4.0.json"  ) {

      echo """
      Please specify the OpenAPI Specification filename you want to deploy:

      Use one of the following provided files:
      - openapi-spec-v1.0.yaml => 1 methods, API Key
      - openapi-spec-v1.1.yaml => 2 methods, API Key
      - openapi-spec-v2.0.yaml => 3 methods, API Key
      - openapi-spec-v3.0.yaml => 3 methods, API Key
      - openapi-spec-v4.0.yaml => 3 methods, API Key

      Use the OPENAPI_SPECIFICATION_FILE parameter to pass the OpenAPI Specification filename you want to deploy.
      """

      error("Use the OPENAPI_SPECIFICATION_FILE parameter to pass the OpenAPI Specification filename you want to deploy.")
    }
  }

  stage('Checkout Source') {
    checkout scm
  }

  stage("Deploy API in Dev") {
    def envName = params.DEV_PROJECT
    def app_name= params.APPLICATION_NAME
    def backend_service = params.DEV_PRIVATE_BASE_URL
	def stagingPublicBaseURL = params.DEV_STAGING_PUBLIC_BASE_URL
	def productionPublicBaseURL = params.DEV_PRODUCTION_PUBLIC_BASE_URL

    // create the ThreescaleService object from your API metadata manifest:
    service = toolbox.prepareThreescaleService(
        openapi: [filename: "cicd/" + params.OPENAPI_SPECIFICATION_FILE ],
        environment: [ baseSystemName: params.API_BASE_SYSTEM_NAME,
                       publicBasePath: "/open-data/",
					   privateBaseUrl: backend_service,
					   stagingPublicBaseURL: stagingPublicBaseURL,
					   productionPublicBaseURL: productionPublicBaseURL,
					   environmentName:  envName ],
        toolbox: [ openshiftProject: params.NAMESPACE,
                   destination: params.TARGET_INSTANCE_DEV,
                   image: params.TOOLBOX_IMAGE_REGISTRY,
                   insecure: params.DISABLE_TLS_VALIDATION == "yes",
                   secretName: params.SECRET_NAME],
        service: [:],
        applications: [
            [ name: "my-test-app", description: "This is used for tests", plan: "sandbox", account: params.DEV_DEVELOPER_ACCOUNT_ID ]
        ],
        applicationPlans: [
          [ systemName: "sandbox", name: "Sandbox", defaultPlan: false, published: true, artefactFile: "https://raw.githubusercontent.com/sgutierr/3scaledemo/master/cicd/sandbox-app-plan.yaml" ]          
	]
    )

    // Import OpenAPI
    service.importOpenAPI()
    echo "Service with system_name ${service.environment.targetSystemName} created !"

    // Add Tags in the description field
    //service.applyDescriptioWithTags()
	  
    service.applyDescriptioWithTags()
	  
    // Create an Application Plan
    service.applyApplicationPlans()

    // Create an Application
    service.applyApplication()
	
    // Wait for saving setup	  
    sleep(time:10,unit:"SECONDS")

    // Run integration tests
    runIntegrationTests(service)
    
    // Promote to production
    service.promoteToProduction()
  }

 stage("Deploy API in TEST") {

    def envName = params.TEST_PROJECT
    def app_name= params.APPLICATION_NAME
    def backend_service = params.TEST_PRIVATE_BASE_URL
	def stagingPublicBaseURL = params.TEST_STAGING_PUBLIC_BASE_URL
	def productionPublicBaseURL = params.TEST_PRODUCTION_PUBLIC_BASE_URL

    // Prepare
    service = toolbox.prepareThreescaleService(
        openapi: [filename: "cicd/" + params.OPENAPI_SPECIFICATION_FILE ],
        environment: [ baseSystemName: params.API_BASE_SYSTEM_NAME,
                       publicBasePath: "/open-data/",
					   privateBaseUrl: backend_service,
					   stagingPublicBaseURL: stagingPublicBaseURL,
					   productionPublicBaseURL: productionPublicBaseURL,
					   environmentName:  envName ],
        toolbox: [ openshiftProject: params.NAMESPACE,
                   destination: params.TARGET_INSTANCE_TEST,
                   image: params.TOOLBOX_IMAGE_REGISTRY,
                   insecure: params.DISABLE_TLS_VALIDATION == "yes",
                   secretName: params.SECRET_NAME],
        service: [:],
        applications: [
            [ name: "my-test-app", description: "This is used for tests", plan: "test", account: params.TEST_DEVELOPER_ACCOUNT_ID ]
        ],
        applicationPlans: [
          [ systemName: "test", name: "Test", defaultPlan: true, published: true ]
        ]
    )
    // Import OpenAPI
    service.importOpenAPI()
    echo "Service with system_name ${service.environment.targetSystemName} created !"

    // Create an Application Plan
    service.applyApplicationPlans()

    // Create an Application
    service.applyApplication()

  }
}
 
def runIntegrationTests(def service) {
  // To run the integration tests when using APIcast SaaS instances, we need
  // to fetch the proxy definition to extract the staging public url
  def proxy = service.readProxy("sandbox")
  def endpointTest = params.ENDPOINT2TEST
  // The integration tests will be a bit different depending on the security scheme
  // declared in the OpenAPI Specification file
  def getCredentialsCodeSnippet = null
  if (service.openapi.securityScheme.name() == "OPEN") {
    getCredentialsCodeSnippet = """
    credential_header="x-dummy: dummy"
    echo "no credential will be used"
    """
  } else if (service.openapi.securityScheme.name() == "APIKEY") {
	def userkey = service.applications[0].userkey
	getCredentialsCodeSnippet = """
	credential_header="api-key: ${userkey}"
	echo "userkey is ${userkey}"
	"""
  } else if (service.openapi.securityScheme.name() == "OIDC") {
    def tokenEndpoint = getTokenEndpoint(params.OIDC_ISSUER_ENDPOINT)
    def clientId = service.applications[0].clientId
    def clientSecret = service.applications[0].clientSecret
    getCredentialsCodeSnippet = """
    echo "token endpoint is ${tokenEndpoint}"
    echo "client_id=${clientId}"
    echo "client_secret=${clientSecret}"
    curl -sfk "${tokenEndpoint}" -d client_id="${clientId}" -d client_secret="${clientSecret}" -d scope=openid -d grant_type=client_credentials -o response.json
    curl -sLfk https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o /tmp/jq
    chmod 755 /tmp/jq
    TOKEN="\$(/tmp/jq -r .access_token response.json)"
    echo "Received access_token '\$TOKEN'"
    credential_header="Authorization: Bearer \$TOKEN"
    """
  }

  // Run the actual tests
  sh """set -e
  echo "Public Staging Base URL is ${proxy.sandbox_endpoint}"
  ${getCredentialsCodeSnippet}
  curl -sfk -w "Get Test List: %{http_code}\n" -o /dev/null "${proxy.sandbox_endpoint}/open-data${endpointTest}" -H "\$credential_header"
  """

}

def getTokenEndpoint(String oidcIssuerEndpoint) {
   def m = (oidcIssuerEndpoint =~ /(https?:\/\/)[^:]+:[^@]+@(.*)/)
   return "${m[0][1]}${m[0][2]}/protocol/openid-connect/token"
}
